---
title: "project"
author: "Gagan Beerappa"
date: "2023-12-03"
output: word_document
---

```{r}
library(ggplot2)
library(ggthemes)
library(lubridate)
library(dplyr)
library(tidyr)
library(tidyverse) # metapackage of all tidyverse packages
library(DT)
library(scales)
library(MASS)
```

```{r}
colors = c("#AA0000", "#CC8450", "#010000", "#777777", "#4500AA", "#FFACDA", "#BACDEF")
colors
```

```{r}
# Read the data for each month separately 
apr <- read.csv("uber-raw-data-apr14.csv")
may <- read.csv("uber-raw-data-may14.csv")
june <- read.csv("uber-raw-data-jun14.csv")
july <- read.csv("uber-raw-data-jul14.csv")
aug <- read.csv("uber-raw-data-aug14.csv")
sept <- read.csv("uber-raw-data-sep14.csv")

# Combine the data together 
data <- rbind(apr, may, june, july, aug, sept)
cat("The dimensions of the data are:", dim(data))

# Print the first 6 rows of the data
head(data)
```

```{r}
data$Date.Time <- as.POSIXct(data$Date.Time, format="%m/%d/%Y %H:%M:%S")
data$Time <- format(as.POSIXct(data$Date.Time, format = "%m/%d/%Y %H:%M:%S"), format="%H:%M:%S")
data$Date.Time <- ymd_hms(data$Date.Time)
```

```{r}
# Create individual columns for month day and year
data$day <- factor(day(data$Date.Time))
data$month <- factor(month(data$Date.Time, label=TRUE))
data$year <- factor(year(data$Date.Time))
data$dayofweek <- factor(wday(data$Date.Time, label=TRUE))
```

```{r}
# Add Time variables as well 
data$second = factor(second(hms(data$Time)))
data$minute = factor(minute(hms(data$Time)))
data$hour = factor(hour(hms(data$Time)))
```

```{r}
# Look at the data
head(data)
```

```{r}
hourly_data <- data %>% 
                    group_by(hour) %>% 
                            dplyr::summarize(Total = n())

# Shos data in a searchable js table
datatable(hourly_data)
```

```{r}
# Plot the data by hour
ggplot(hourly_data, aes(hour, Total)) + 
geom_bar(stat="identity", 
         color="black") + 
ggtitle("Trips Every Hour") + 
theme(legend.position = "none") + 
scale_y_continuous(labels=comma) + theme_bw()
```


```{r}
# Aggregate the data by month and hour
month_hour_data <- data %>% group_by(month, hour) %>%  dplyr::summarize(Total = n())

ggplot(month_hour_data, aes(hour, Total, fill=month)) + 
geom_bar(stat = "identity") + 
ggtitle("Trips by Hour and Month") + 
scale_y_continuous(labels = comma)
```

```{r}
# Aggregate data by day of the month 
day_data <- data %>% group_by(day) %>% dplyr::summarize(Trips = n())
day_data
```

```{r}
# Plot the data for the day
ggplot(day_data, aes(day, Trips)) + 
geom_bar(stat = "identity", fill = "pink") +
ggtitle("Trips by day of the month") + 
theme(legend.position = "none") + 
scale_y_continuous(labels = comma) + theme_bw()
```

```{r}
day_month_data <- data %>% group_by(dayofweek, month) %>% dplyr::summarize(Trips = n())
day_month_data

```

```{r}
# Plot the above data
ggplot(day_month_data, aes(dayofweek, Trips, fill = month)) + 
geom_bar(stat = "identity", aes(fill = month), position = "dodge") + 
ggtitle("Trias by Day and Month") + 
scale_y_continuous(labels = comma) + 
scale_fill_manual(values = colors)
```

```{r}
month_data <- data %>% group_by(month) %>% dplyr::summarize(Total = n())
ggplot(month_data, aes(month, Total, fill = month)) + 
geom_bar(stat = "Identity") + 
ggtitle("Trips in a month") + 
theme(legend.position = "none") + 
scale_y_continuous(labels = comma) + 
scale_fill_manual(values = colors) + theme_bw()
month_data
```

```{r}
day_hour_data <- data %>% group_by(day, hour) %>% dplyr::summarize(Total = n())
datatable(day_hour_data)
```

```{r}
# Plot a heatmap 

ggplot(day_hour_data, aes(day, hour, fill = Total)) + 
geom_tile(color = "white") + 
ggtitle("Heat Map by Hour and Day")
```

```{r}
# Collect data by month and day

month_day_data <- data %>% group_by(month, day) %>% dplyr::summarize(Trips = n())
month_day_data
```

```{r}
# Plot a heatmap 

ggplot(month_day_data, aes(day, month, fill = Trips)) + 
geom_tile(color = "white") + 
ggtitle("Heat Map by Month and Day") + theme_bw()
```

```{r}
# Plot a heatmap by day of the week and month

ggplot(day_month_data, aes(dayofweek, month, fill = Trips)) + 
geom_tile(color = "white") + 
ggtitle("Heat Map by Month and Day") + theme_bw()
```

```{r}
# Set Map Constants
min_lat <- 40 
max_lat <- 40.91
min_long <- -74.15
max_long <- -73.7004
ggplot(data, aes(x=Lon, y=Lat)) +
  geom_point(size=1, color = "grey") +
     scale_x_continuous(limits=c(min_long, max_long)) +
      scale_y_continuous(limits=c(min_lat, max_lat)) +
        theme_map() +
           ggtitle("NYC MAP BASED ON UBER RIDES DURING 2014 (APR-SEP)")
```

Fit a simple linear regression model with number of trips as the response and Days as the predictor

```{r}
head(month_day_data)
lmfit.month <- lm(Trips ~ day, data = month_day_data)
lmfit.month
```

```{r}
summary(lmfit.month)
```
```{r}
confint(lmfit.month)
```


```{r}
attach(month_day_data)
# least squares regression line
plot(day, Trips)
abline(lmfit.month)
```

```{r}
plot(predict(lmfit.month), residuals(lmfit.month))
```


```{r}
plot(hatvalues(lmfit.month))
which.max(hatvalues(lmfit.month))
```


Fit a simple linear regression model with number of trips as the response and Months as the predictor

```{r}
head(month_data)
lmfit.month <- lm(Trips ~ day, data = month_data)
lmfit.month
```

```{r}
summary(lmfit.month)
```
```{r}
confint(lmfit.month)
```


```{r}
attach(month_day_data)
# least squares regression line
plot(day, Trips)
abline(lmfit.month)
```

```{r}
plot(predict(lmfit.month), residuals(lmfit.month))
```


```{r}
plot(hatvalues(lmfit.month))
which.max(hatvalues(lmfit.month))
```


Fit a simple linear regression model with number of trips as the response and Days as the predictor

```{r}
head(day_hour_data)
lmfit.day <- lm(Trips ~ day, data = day_hour_data)
lmfit.day
```

```{r}
summary(lmfit.day)
```
```{r}
confint(lmfit.day)
```


```{r}
attach(day_data)
# least squares regression line
plot(day, Trips)
abline(lmfit.day)
```

```{r}
plot(predict(lmfit.day), residuals(lmfit.day))
```


```{r}
plot(hatvalues(lmfit.day))
which.max(hatvalues(lmfit.day))
```